-- Widget Custom data and order, order = 0 disabled widget
return {
	data = {
		AdvPlayersList = {
			expandDown = false,
			expandLeft = true,
			m_IDActive = false,
			m_chatActive = true,
			m_cpupingActive = true,
			m_nameActive = true,
			m_pointActive = true,
			m_seespecActive = true,
			m_shareActive = true,
			m_sideActive = true,
			m_specActive = true,
			m_takeActive = true,
			vsx = 1920,
			vsy = 1080,
			widgetPosX = 1682,
			widgetPosY = 0,
			widgetRight = 1920,
			widgetTop = 100,
		},
		["Ally Resource Bars"] = {
			h = 14,
			x1 = 1776,
			y1 = 724,
		},
		BtEvaluator = {
			selected = "library",
		},
		CustomFormations2 = {
			maxHungarianUnits = 20,
		},
		["EPIC Menu"] = {
			country = "XX",
			lang = "en",
			music_volume = 0.5,
			show_crudemenu = true,
			sub_pos_x = 960,
			sub_pos_y = 540,
			versionmin = 50,
			wl_h = 756,
			wl_w = 300,
			wl_x = 810,
			wl_y = 162,
			config = {},
			keybounditems = {
				epic_notachili_widget_selector_widgetlist = {
					key = "f11",
					mod = "",
				},
				["luaui tweakgui"] = {
					key = "f11",
					mod = "",
				},
				pause = {
					key = "pause",
					mod = "",
				},
				slowdown = {
					key = "-",
					mod = "A+",
				},
				speedup = {
					key = "",
					mod = "A+",
				},
				viewfps = {
					key = "f1",
					mod = "C+",
				},
				viewfree = {
					key = "f5",
					mod = "C+",
				},
				viewrot = {
					key = "f4",
					mod = "C+",
				},
				viewta = {
					key = "f2",
					mod = "C+",
				},
			},
			widgets = {},
		},
		["FactoryQ Manager"] = {},
		["Red Console"] = {
			Config = {
				console = {
					fadedistance = 100,
					fadetime = 0.25,
					filterduplicates = true,
					fontsize = 11,
					margin = 5,
					maxage = 15,
					maxlines = 10,
					minlines = 1,
					px = 300,
					py = 39,
					sx = 605,
					callytext = {
						[1] = 0,
						[2] = 1,
						[3] = 0,
						[4] = 1,
					},
					cbackground = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 0.1,
					},
					cborder = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 0.5,
					},
					cgametext = {
						[1] = 0.40000001,
						[2] = 1,
						[3] = 1,
						[4] = 1,
					},
					cmisctext = {
						[1] = 0.77999997,
						[2] = 0.77999997,
						[3] = 0.77999997,
						[4] = 1,
					},
					cotherallytext = {
						[1] = 1,
						[2] = 0.5,
						[3] = 0.5,
						[4] = 1,
					},
					cothertext = {
						[1] = 1,
						[2] = 1,
						[3] = 1,
						[4] = 1,
					},
					cspectext = {
						[1] = 1,
						[2] = 1,
						[3] = 0,
						[4] = 1,
					},
					dragbutton = {
						[1] = 2,
					},
					tooltip = {
						background = "Hold ÿÿÿmiddle mouse buttonÿÿÿÿ to drag the console around.\
\
Press ÿÿÿCTRLÿÿÿÿ while mouse is above the console to activate chatlog viewing.\
Use mousewheel (+hold ÿÿÿSHIFTÿÿÿÿ for speedup) to scroll through the chatlog.",
					},
				},
			},
		},
		["Volume OSD"] = {
			widgetPosX = 640,
			widgetPosY = 180,
		},
	},
	order = {
		AdvPlayersList = 11,
		["Air ground area attack"] = 17,
		["Air loopback default"] = 18,
		["Ally Resource Bars"] = 9,
		["Ally Selected Units"] = 19,
		AllyCursors = 12345,
		["Armor Display"] = 52,
		["Attack AoE"] = 49,
		["Attack area"] = 50,
		Autoquit = 20,
		BA_AllyCursors = 59,
		["Bloom Shader"] = 0,
		BtCheat = 21,
		BtCommands = 45,
		BtController = 48,
		BtCreator = 47,
		BtEvaluator = 46,
		BtOS = 22,
		["Build costs 1.02"] = 0,
		BuildETA = 13,
		CameraShakey = 23,
		["Chili Framework Cloned"] = 6,
		["Clever gathering point"] = 24,
		["Commander Name Tags1.0"] = 7,
		["Context Menu"] = 25,
		CustomFormations2 = 62,
		["EPIC Menu"] = 3,
		["Easy Facing"] = 26,
		["External VR Grid"] = 12,
		["Factory Auto-Repeat"] = 27,
		["Factory hold position"] = 28,
		["FactoryQ Manager"] = 5,
		["Ghost Radar"] = 29,
		["Ghost Site"] = 30,
		HealthBars = 8,
		["Idle air fly default"] = 31,
		["Improved MetalMakers"] = 32,
		["Jumjet GUI"] = 63,
		LoIUI = 0,
		["Lua Console"] = 33,
		Lups = 61,
		LupsManager = 57,
		LupsStats = 0,
		["Measure distance"] = 0,
		["Mouse Buildspacing"] = 60,
		["NotAchili Cursor Tip 3"] = 34,
		["NotAchili Framework"] = 1,
		["NotAchili Nota UI"] = 65,
		["NotAchili Vote Display"] = 10,
		["NotAchili Widget Selector"] = 4,
		["Nota Exit Screen"] = 66,
		["Nota Minimap"] = 67,
		Orders = 14,
		["Pause Screen"] = 35,
		["Point Tracker"] = 36,
		["Projectile lights"] = 15,
		Prospector = 51,
		["Rank Icons"] = 55,
		ReclaimInfo = 37,
		["Red Build/Order Menu"] = 0,
		["Red Console"] = 0,
		["Red Minimap"] = 0,
		["Red Resource Bars"] = 0,
		["Red Tooltip"] = 0,
		Red_Drawing = 0,
		Red_UI_Framework = 0,
		["RoN Taunts"] = 12345,
		["Select army only"] = 53,
		["Select n Center!"] = 60,
		SelectionButtons = 0,
		["Shared Functions"] = 2,
		["Show Orders"] = 38,
		SmartAreaReclaim = 39,
		SmoothCam = 40,
		["Stall Assist"] = 48,
		["Start Point Remover"] = 50,
		StartRadius = 51,
		Stockpiler = 41,
		TacticalGrid = 0,
		TacticalSelection = 68,
		TeamPlatter = 0,
		["Teleport GUI"] = 64,
		Transporting = 0,
		["Unit Marker"] = 42,
		["Unit Stats"] = 0,
		UnitShapes = 54,
		["Units on Fire"] = 58,
		["Volume OSD"] = 43,
		["default radar view"] = 44,
		exampleDrawDebugLines = 16,
		gui_ai_marker = 56,
		threatAreasDebug = 0,
	},
}
